### ISSUE TITLE
Build error when using lib

### ISSUE THREAD

**Issue by vim-zz** [TeXitoi/osmpbfreader-rs#46] opened 2023-08-20 19:51 UTC
I tried using the lib by adding to my project deps, and got this error

1. Ran `cargo add osmpbfreader`
2. Cargo.toml now has `osmpbfreader = "0.16.0"` under `[dependencies]`       
3. When running `cargo build`, I got:

```
error[E0433]: failed to resolve: could not find `Codegen` in `protobuf_codegen_pure`
  --> /Users/myname/.cargo/registry/src/index.crates.io-6f17d22bba15001f/osmpbfreader-0.16.0/build.rs:16:28
   |
16 |     protobuf_codegen_pure::Codegen::new()
   |                            ^^^^^^^ could not find `Codegen` in `protobuf_codegen_pure`
```

After adding this dep, I could get it work:
1. `cargo add protobuf-codegen-pure`
2. Cargo.toml now has `protobuf-codegen-pure = "2.28.0"` under `[dependencies]`     
3. When running `cargo build` it works

Could thie dependency missing from the lib?

**Comment by TeXitoi** [comment] 2024-02-26 10:42
I can't reproduce. I suppose it was a bug in the protobuf crate that is now fixed. If you have a scenario to reproduce, feel free to reopen.

**Closed by TeXitoi** 2024-02-26 10:42 UTC
